package com.asher9.compactblocks;

import java.io.File;

import com.asher9.compactblocks.api.Events;
import com.asher9.compactblocks.config.Config;
import com.asher9.compactblocks.proxies.CommonProxy;
import com.asher9.compactblocks.utils.UpdateChecker;
import net.minecraft.util.text.TextFormatting;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.fml.client.event.ConfigChangedEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;

@Mod(modid = Reference.MODID, name = Reference.MODNAME, version = Reference.VERSION,
        guiFactory = Reference.GuiFactory)

public class CompactBlocks {

    public static Config config;

    @SidedProxy(clientSide = Reference.ClientSide, serverSide = Reference.ServerSide)
    private static CommonProxy proxy;

    @EventHandler
    public void preInit(FMLPreInitializationEvent event) {

        //Mod Info
        ModMetadata data = event.getModMetadata();
        data.autogenerated = false;
        data.name = TextFormatting.GREEN + Reference.MODNAME;
        data.credits = TextFormatting.BLUE + "Asher_9";
        data.authorList.add("Asher_9");
        data.version = Reference.VERSION;
        data.modId = Reference.MODID;

        //Config File
        File configDir = new File(event.getModConfigurationDirectory(), "CompactBlocks");
        config = new Config(new File(configDir, "CompactBlocks.cfg"));

        //CInit.initAll();
        //CModItems.register();
        //CModBlocks.register();

        proxy.registerRenders();
    }

    @EventHandler
    public void init(FMLInitializationEvent event) {
        if(event.getSide().isClient() && CompactBlocks.config.cache.checkUpdates) {
            MinecraftForge.EVENT_BUS.register(new Events());
            UpdateChecker.init();
        }

        proxy.init();
        //OreDictHandler.OreDictionary();
        proxy.registerModelBakery();
        //CreativeTabCreator.Init();
        //CShapelessCraftingRecipe.ShapelessCraftingRecipe();
        //CShapedCraftingRecipe.ShapedRecipe();
        //CFurnaceRecipes.furnaceRecipes();
    }

    @EventHandler
    public void postInit(FMLPostInitializationEvent event) {



    }

    @SubscribeEvent
    public void onConfigChanged (ConfigChangedEvent.OnConfigChangedEvent event) {
        if (event.getModID().equals(Reference.MODID))
            config.syncConfig();
    }
}
