package com.asher9.CompactBlocks;

import com.asher9.CompactBlocks.config.Config;
import com.asher9.CompactBlocks.proxies.CommonProxy;
import net.minecraft.util.text.TextFormatting;
import net.minecraftforge.fml.client.event.ConfigChangedEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;

import java.io.File;


@Mod(modid = Reference.MODID, name = Reference.MODNAME, version = Reference.VERSION, guiFactory = Reference.GuiFactory)

public class CompactBlocks {

    public static Config config;

    @SidedProxy(clientSide = Reference.ClientSide, serverSide = Reference.ServerSide)
    private static CommonProxy proxy;

    @Mod.EventHandler
    public void preInit(FMLPreInitializationEvent event) {
        //Mod Info
        ModMetadata data = event.getModMetadata();
        data.autogenerated = false;
        data.name = TextFormatting.GREEN + Reference.MODNAME;
        data.credits = TextFormatting.BLUE + "Asher_9";
        data.authorList.add("Asher_9");
        data.version = Reference.VERSION;
        data.modId = Reference.MODID;

        //Config File
         File configDir = new File(event.getModConfigurationDirectory(), "CompactBlocks");
         config = new Config(new File(configDir, "CompactBlocks.cfg"));

         proxy.registerRenders();
    }

    @Mod.EventHandler
    public void init(FMLInitializationEvent event) {

    }

    @Mod.EventHandler
    public void postInit(FMLPostInitializationEvent event) {

    }

    @SubscribeEvent
    public void onConfigChanged(ConfigChangedEvent.OnConfigChangedEvent event) {
        if(event.getModID().equals(Reference.MODID)) {
            config.syncConfig();
        }
    }

}
