package com.asher9.CompactBlocks.api;

import com.asher9.CompactBlocks.init.CBlocks;
import com.asher9.CompactBlocks.init.CItems;
import com.asher9.CompactBlocks.util.CLogger;

import net.minecraft.item.ItemStack;
import net.minecraftforge.oredict.OreDictionary;

public class OreDictHandler {
	
	public static void OreDictionary() {
		 CLogger.getLogger().info("Loading Items into Ore Dictionary...");

		 OreDictionary.registerOre("ingotEnderium", new ItemStack(CItems.ingotEnderium));
		 OreDictionary.registerOre("blockEnderium", CBlocks.blockEnderium);
		 OreDictionary.registerOre("oreEnderium", CBlocks.oreEnderium);
		 OreDictionary.registerOre("oreNetherEnderium", CBlocks.oreNetherEnderium);
		 OreDictionary.registerOre("oreEndEnderium", CBlocks.oreEndEnderium);
		 OreDictionary.registerOre("nuggetEnderium", CItems.nuggetEnderium);
		 OreDictionary.registerOre("dustEnderium", CItems.dustEnderium);
		 OreDictionary.registerOre("compressed1xCobblestone", CBlocks.compressedCobblestone);
		 OreDictionary.registerOre("compressed2xCobblestone", CBlocks.doublecompressedCobblestone);
		 OreDictionary.registerOre("compressed3xCobblestone", CBlocks.triplecompressedCobblestone);
		 OreDictionary.registerOre("compressed4xCobblestone", CBlocks.quadruplecompressedCobblestone);
		 OreDictionary.registerOre("compressed1xDirt", CBlocks.compressedDirt);
		 OreDictionary.registerOre("compressed2xDirt", CBlocks.doublecompressedDirt);
		 OreDictionary.registerOre("compressed3xDirt", CBlocks.triplecompressedDirt);
		 OreDictionary.registerOre("compressed4xDirt", CBlocks.quadruplecompressedDirt);
		 OreDictionary.registerOre("compressed1xGravel", CBlocks.compressedGravel);
		 OreDictionary.registerOre("compressed2xGravel", CBlocks.doublecompressedGravel);
		 OreDictionary.registerOre("compressed3xGravel", CBlocks.triplecompressedGravel);
		 OreDictionary.registerOre("compressed4xGravel", CBlocks.quadruplecompressedGravel);
		 OreDictionary.registerOre("compressed1xSand", CBlocks.compressedSand);
		 OreDictionary.registerOre("compressed2xSand", CBlocks.doublecompressedSand);
		 OreDictionary.registerOre("compressed3xSand", CBlocks.triplecompressedSand);
		 OreDictionary.registerOre("compressed4xSand", CBlocks.quadruplecompressedSand);
		 OreDictionary.registerOre("compressed1xBedrock", CBlocks.compressedBedrock);
		 OreDictionary.registerOre("compressed2xBedrock", CBlocks.doublecompressedBedrock);
		 OreDictionary.registerOre("compressed3xBedrock", CBlocks.triplecompressedBedrock);
		 OreDictionary.registerOre("compressed4xBedrock", CBlocks.quadruplecompressedBedrock);
		 OreDictionary.registerOre("compressed1xBrick", CBlocks.compressedBrick);
		 OreDictionary.registerOre("compressed2xBrick", CBlocks.doublecompressedBrick);
		 OreDictionary.registerOre("compressed3xBrick", CBlocks.triplecompressedBrick);
		 OreDictionary.registerOre("compressed4xBrick", CBlocks.quadruplecompressedBrick);
		 OreDictionary.registerOre("compressed1xClay", CBlocks.compressedClay);
		 OreDictionary.registerOre("compressed2xClay", CBlocks.doublecompressedClay);
		 OreDictionary.registerOre("compressed3xClay", CBlocks.triplecompressedClay);
		 OreDictionary.registerOre("compressed4xClay", CBlocks.quadruplecompressedClay);
		 OreDictionary.registerOre("compressed1xCoalBlock", CBlocks.compressedCoalBlock);
		 OreDictionary.registerOre("compressed2xCoalBlock", CBlocks.doublecompressedCoalBlock);
		 OreDictionary.registerOre("compressed3xCoalBlock", CBlocks.triplecompressedCoalBlock);
		 OreDictionary.registerOre("compressed4xCoalBlock", CBlocks.quadruplecompressedCoalBlock);
		 OreDictionary.registerOre("compressed1xCobblestone_mossy", CBlocks.compressedCobblestone_mossy);
		 OreDictionary.registerOre("compressed2xCobblestone_mossy", CBlocks.doublecompressedCobblestone_mossy);
		 OreDictionary.registerOre("compressed3xCobblestone_mossy", CBlocks.triplecompressedCobblestone_mossy);
		 OreDictionary.registerOre("compressed4xCobblestone_mossy", CBlocks.quadruplecompressedCobblestone_mossy);
		 OreDictionary.registerOre("compressed1xEnderium", CBlocks.compressedEnderium);
		 OreDictionary.registerOre("compressed2xEnderium", CBlocks.doublecompressedEnderium);
		 OreDictionary.registerOre("compressed3xEnderium", CBlocks.triplecompressedEnderium);
		 OreDictionary.registerOre("compressed4xEnderium", CBlocks.quadruplecompressedEnderium);
		 OreDictionary.registerOre("compressed1xObsidian", CBlocks.compressedObsidian);
		 OreDictionary.registerOre("compressed2xObsidian", CBlocks.doublecompressedObsidian);
		 OreDictionary.registerOre("compressed3xObsidian", CBlocks.triplecompressedObsidian);
		 OreDictionary.registerOre("compressed4xObsidian", CBlocks.quadruplecompressedObsidian);
		 OreDictionary.registerOre("compressed1xStone", CBlocks.compressedStone);
		 OreDictionary.registerOre("compressed2xStone", CBlocks.doublecompressedStone);
		 OreDictionary.registerOre("compressed3xStone", CBlocks.triplecompressedStone);
		 OreDictionary.registerOre("compressed4xStone", CBlocks.quadruplecompressedStone);
		 OreDictionary.registerOre("compressed1xDiamondBlock", CBlocks.compressedDiamondBlock);
		 OreDictionary.registerOre("compressed2xDiamondBlock", CBlocks.doublecompressedDiamondBlock);
		 OreDictionary.registerOre("compressed3xDiamondBlock", CBlocks.triplecompressedDiamondBlock);
		 OreDictionary.registerOre("compressed4xDiamondBlock", CBlocks.quadruplecompressedDiamondBlock);
		 OreDictionary.registerOre("compressed1xEmeraldBlock", CBlocks.compressedEmeraldBlock);
		 OreDictionary.registerOre("compressed2xEmeraldBlock", CBlocks.doublecompressedEmeraldBlock);
		 OreDictionary.registerOre("compressed3xEmeraldBlock", CBlocks.triplecompressedEmeraldBlock);
		 OreDictionary.registerOre("compressed4xEmeraldBlock", CBlocks.quadruplecompressedEmeraldBlock);
		 OreDictionary.registerOre("compressed1xEndStone", CBlocks.compressedEndStone);
		 OreDictionary.registerOre("compressed2xEndStone", CBlocks.doublecompressedEndStone);
		 OreDictionary.registerOre("compressed3xEndStone", CBlocks.triplecompressedEndStone);
		 OreDictionary.registerOre("compressed4xEndStone", CBlocks.quadruplecompressedEndStone);
		 OreDictionary.registerOre("compressed1xGlowstone", CBlocks.compressedGlowstone);
		 OreDictionary.registerOre("compressed2xGlowstone", CBlocks.doublecompressedGlowstone);
		 OreDictionary.registerOre("compressed3xGlowstone", CBlocks.triplecompressedGlowstone);
		 OreDictionary.registerOre("compressed4xGlowstone", CBlocks.quadruplecompressedGlowstone);
		 OreDictionary.registerOre("compressed1xGlassBlock", CBlocks.compressedGlassBlock);
		 OreDictionary.registerOre("compressed2xGlassBlock", CBlocks.doublecompressedGlassBlock);
		 OreDictionary.registerOre("compressed3xGlassBlock", CBlocks.triplecompressedGlassBlock);
		 OreDictionary.registerOre("compressed4xGlassBlock", CBlocks.quadruplecompressedGlassBlock);
		 OreDictionary.registerOre("compressed1xGoldBlock", CBlocks.compressedGoldBlock);
		 OreDictionary.registerOre("compressed2xGoldBlock", CBlocks.doublecompressedGoldBlock);
		 OreDictionary.registerOre("compressed3xGoldBlock", CBlocks.triplecompressedGoldBlock);
		 OreDictionary.registerOre("compressed4xGoldBlock", CBlocks.quadruplecompressedGoldBlock);
		 OreDictionary.registerOre("compressed1xHayBlock", CBlocks.compressedHayBlock);
		 OreDictionary.registerOre("compressed2xHayBlock", CBlocks.doublecompressedHayBlock);
		 OreDictionary.registerOre("compressed3xHayBlock", CBlocks.triplecompressedHayBlock);
		 OreDictionary.registerOre("compressed4xHayBlock", CBlocks.quadruplecompressedHayBlock);
		 OreDictionary.registerOre("compressed1xIce", CBlocks.compressedIce);
		 OreDictionary.registerOre("compressed2xIce", CBlocks.doublecompressedIce);
		 OreDictionary.registerOre("compressed3xIce", CBlocks.triplecompressedIce);
		 OreDictionary.registerOre("compressed4xIce", CBlocks.quadruplecompressedIce);
		 OreDictionary.registerOre("compressed1xIronBlock", CBlocks.compressedIronBlock);
		 OreDictionary.registerOre("compressed2xIronBlock", CBlocks.doublecompressedIronBlock);
		 OreDictionary.registerOre("compressed3xIronBlock", CBlocks.triplecompressedIronBlock);
		 OreDictionary.registerOre("compressed4xIronBlock", CBlocks.quadruplecompressedIronBlock);
		 OreDictionary.registerOre("compressed1xLapisBlock", CBlocks.compressedLapisBlock);
		 OreDictionary.registerOre("compressed2xLapisBlock", CBlocks.doublecompressedLapisBlock);
		 OreDictionary.registerOre("compressed3xLapisBlock", CBlocks.triplecompressedLapisBlock);
		 OreDictionary.registerOre("compressed4xLapisBlock", CBlocks.quadruplecompressedLapisBlock);
		 OreDictionary.registerOre("compressed1xNetherBrick", CBlocks.compressedNetherBrick);
		 OreDictionary.registerOre("compressed2xNetherBrick", CBlocks.doublecompressedNetherBrick);
		 OreDictionary.registerOre("compressed3xNetherBrick", CBlocks.triplecompressedNetherBrick);
		 OreDictionary.registerOre("compressed4xNetherBrick", CBlocks.quadruplecompressedNetherBrick);
		 for (int i = 0; i < EnumHandler.WoodTypes.values().length; i++) {
			 OreDictionary.registerOre("compressed1xWoodPlanks", (new ItemStack(CBlocks.compressedWoodPlanks, i)));
			 OreDictionary.registerOre("compressed2xWoodPlanks", (new ItemStack(CBlocks.doublecompressedWoodPlanks, i)));
			 OreDictionary.registerOre("compressed3xWoodPlanks", (new ItemStack(CBlocks.triplecompressedWoodPlanks, i)));
			 OreDictionary.registerOre("compressed4xWoodPlanks", (new ItemStack(CBlocks.quadruplecompressedWoodPlanks, i)));
		 }
		 OreDictionary.registerOre("compressed1xNetherrack", CBlocks.compressedNetherrack);
		 OreDictionary.registerOre("compressed2xNetherrack", CBlocks.doublecompressedNetherrack);
		 OreDictionary.registerOre("compressed3xNetherrack", CBlocks.triplecompressedNetherrack);
		 OreDictionary.registerOre("compressed4xNetherrack", CBlocks.quadruplecompressedNetherrack);
		 OreDictionary.registerOre("compressed1xRedstoneBlock", CBlocks.compressedRedstoneBlock);
		 OreDictionary.registerOre("compressed2xRedstoneBlock", CBlocks.doublecompressedRedstoneBlock);
		 OreDictionary.registerOre("compressed3xRedstoneBlock", CBlocks.triplecompressedRedstoneBlock);
		 OreDictionary.registerOre("compressed4xRedstoneBlock", CBlocks.quadruplecompressedRedstoneBlock);
		 OreDictionary.registerOre("compressed1xRedSand", CBlocks.compressedRedSand);
		 OreDictionary.registerOre("compressed2xRedSand", CBlocks.doublecompressedRedSand);
		 OreDictionary.registerOre("compressed3xRedSand", CBlocks.triplecompressedRedSand);
		 OreDictionary.registerOre("compressed4xRedSand", CBlocks.quadruplecompressedRedSand);
		 OreDictionary.registerOre("compressed1xStoneBrick", CBlocks.compressedStoneBrick);
		 OreDictionary.registerOre("compressed2xStoneBrick", CBlocks.doublecompressedStoneBrick);
		 OreDictionary.registerOre("compressed3xStoneBrick", CBlocks.triplecompressedStoneBrick);
		 OreDictionary.registerOre("compressed4xStoneBrick", CBlocks.quadruplecompressedStoneBrick);
		 OreDictionary.registerOre("compressed1xStoneBrickChiseled", CBlocks.compressedStoneBrickChiseled);
		 OreDictionary.registerOre("compressed2xStoneBrickChiseled", CBlocks.doublecompressedStoneBrickChiseled);
		 OreDictionary.registerOre("compressed3xStoneBrickChiseled", CBlocks.triplecompressedStoneBrickChiseled);
		 OreDictionary.registerOre("compressed4xStoneBrickChiseled", CBlocks.quadruplecompressedStoneBrickChiseled);
		 OreDictionary.registerOre("compressed1xStoneBrickCracked", CBlocks.compressedStoneBrickCracked);
		 OreDictionary.registerOre("compressed2xStoneBrickCracked", CBlocks.doublecompressedStoneBrickCracked);
		 OreDictionary.registerOre("compressed3xStoneBrickCracked", CBlocks.triplecompressedStoneBrickCracked);
		 OreDictionary.registerOre("compressed4xStoneBrickCracked", CBlocks.quadruplecompressedStoneBrickCracked);
		 OreDictionary.registerOre("compressed1xStoneBrickMossy", CBlocks.compressedStoneBrickMossy);
		 OreDictionary.registerOre("compressed2xStoneBrickMossy", CBlocks.doublecompressedStoneBrickMossy);
		 OreDictionary.registerOre("compressed3xStoneBrickMossy", CBlocks.triplecompressedStoneBrickMossy);
		 OreDictionary.registerOre("compressed4xStoneBrickMossy", CBlocks.quadruplecompressedStoneBrickMossy);
		 OreDictionary.registerOre("compressed1xSponge", CBlocks.compressedSponge);
		 OreDictionary.registerOre("compressed2xSponge", CBlocks.doublecompressedSponge);
		 OreDictionary.registerOre("compressed3xSponge", CBlocks.triplecompressedSponge);
		 OreDictionary.registerOre("compressed4xSponge", CBlocks.quadruplecompressedSponge);
		 for (int i = 0; i < EnumHandler.ColorTypes.values().length; i++) {
			 OreDictionary.registerOre("compressed1xWool", new ItemStack(CBlocks.compressedWool, i));
			 OreDictionary.registerOre("compressed2xWool", new ItemStack(CBlocks.doublecompressedWool, i));
			 OreDictionary.registerOre("compressed3xWool", new ItemStack(CBlocks.triplecompressedWool, i));
			 OreDictionary.registerOre("compressed4xWool", new ItemStack(CBlocks.quadruplecompressedWool, i));
		 }
		 OreDictionary.registerOre("compressed1xBookshelf", CBlocks.compressedBookshelf);
		 OreDictionary.registerOre("compressed2xBookshelf", CBlocks.doublecompressedBookshelf);
		 OreDictionary.registerOre("compressed3xBookshelf", CBlocks.triplecompressedBookshelf);
		 OreDictionary.registerOre("compressed4xBookshelf", CBlocks.quadruplecompressedBookshelf);
		 OreDictionary.registerOre("compressed1xCraftingTable", CBlocks.compressedCraftingTable);
		 OreDictionary.registerOre("compressed2xCraftingTable", CBlocks.doublecompressedCraftingTable);
		 OreDictionary.registerOre("compressed3xCraftingTable", CBlocks.triplecompressedCraftingTable);
		 OreDictionary.registerOre("compressed4xCraftingTable", CBlocks.quadruplecompressedCraftingTable);
		 for (int i = 0; i < EnumHandler.ColorTypes.values().length; i++) {
			 OreDictionary.registerOre("compressed1xColorGlass", new ItemStack(CBlocks.compressedColorGlass, i));
			 OreDictionary.registerOre("compressed2xColorGlass", new ItemStack(CBlocks.doublecompressedColorGlass, i));
			 OreDictionary.registerOre("compressed3xColorGlass", new ItemStack(CBlocks.triplecompressedColorGlass, i));
			 OreDictionary.registerOre("compressed4xColorGlass", new ItemStack(CBlocks.quadruplecompressedColorGlass, i));
		 }
		 OreDictionary.registerOre("compressed1xHardenedClay", CBlocks.compressedHardenedClay_ST);
		 OreDictionary.registerOre("compressed2xHardenedClay", CBlocks.doublecompressedHardenedClay_ST);
		 OreDictionary.registerOre("compressed3xHardenedClay", CBlocks.triplecompressedHardenedClay_ST);
		 OreDictionary.registerOre("compressed4xHardenedClay", CBlocks.quadruplecompressedHardenedClay_ST);
		 for (int i = 0; i < EnumHandler.ColorTypes.values().length; i++) {
			 OreDictionary.registerOre("compressed1xColorHardenedClay", new ItemStack(CBlocks.compressedHardenedClay, i));
			 OreDictionary.registerOre("compressed2xColorHardenedClay", new ItemStack(CBlocks.doublecompressedHardenedClay, i));
		 	 OreDictionary.registerOre("compressed3xColorHardenedClay", new ItemStack(CBlocks.triplecompressedHardenedClay, i));
		 	 OreDictionary.registerOre("compressed4xColorHardenedClay", new ItemStack(CBlocks.quadruplecompressedHardenedClay, i));
	     }
		 OreDictionary.registerOre("compressed1xCoalOre", CBlocks.compressedCoalOre);
		 OreDictionary.registerOre("compressed2xCoalOre", CBlocks.doublecompressedCoalOre);
		 OreDictionary.registerOre("compressed3xCoalOre", CBlocks.triplecompressedCoalOre);
		 OreDictionary.registerOre("compressed4xCoalOre", CBlocks.quadruplecompressedCoalOre);
		 OreDictionary.registerOre("compressed1xDiamondOre", CBlocks.compressedDiamondOre);
		 OreDictionary.registerOre("compressed2xDiamondOre", CBlocks.doublecompressedDiamondOre);
		 OreDictionary.registerOre("compressed3xDiamondOre", CBlocks.triplecompressedDiamondOre);
		 OreDictionary.registerOre("compressed4xDiamondOre", CBlocks.quadruplecompressedDiamondOre);
		 OreDictionary.registerOre("compressed1xEmeraldOre", CBlocks.compressedEmeraldOre);
		 OreDictionary.registerOre("compressed2xEmeraldOre", CBlocks.doublecompressedEmeraldOre);
		 OreDictionary.registerOre("compressed3xEmeraldOre", CBlocks.triplecompressedEmeraldOre);
		 OreDictionary.registerOre("compressed4xEmeraldOre", CBlocks.quadruplecompressedEmeraldOre);
		 OreDictionary.registerOre("compressed1xGoldOre", CBlocks.compressedGoldOre);
		 OreDictionary.registerOre("compressed2xGoldOre", CBlocks.doublecompressedGoldOre);
		 OreDictionary.registerOre("compressed3xGoldOre", CBlocks.triplecompressedGoldOre);
		 OreDictionary.registerOre("compressed4xGoldOre", CBlocks.quadruplecompressedGoldOre);
		 OreDictionary.registerOre("compressed1xIronOre", CBlocks.compressedIronOre);
		 OreDictionary.registerOre("compressed2xIronOre", CBlocks.doublecompressedIronOre);
		 OreDictionary.registerOre("compressed3xIronOre", CBlocks.triplecompressedIronOre);
		 OreDictionary.registerOre("compressed4xIronOre", CBlocks.quadruplecompressedIronOre);
		 OreDictionary.registerOre("compressed1xPodzol", CBlocks.compressedPodzol);
		 OreDictionary.registerOre("compressed2xPodzol", CBlocks.doublecompressedPodzol);
		 OreDictionary.registerOre("compressed3xPodzol", CBlocks.triplecompressedPodzol);
		 OreDictionary.registerOre("compressed4xPodzol", CBlocks.quadruplecompressedPodzol);
		 OreDictionary.registerOre("compressed1xQuartzBlock", CBlocks.compressedQuartzBlock);
		 OreDictionary.registerOre("compressed2xQuartzBlock", CBlocks.doublecompressedQuartzBlock);
		 OreDictionary.registerOre("compressed3xQuartzBlock", CBlocks.triplecompressedQuartzBlock);
		 OreDictionary.registerOre("compressed4xQuartzBlock", CBlocks.quadruplecompressedQuartzBlock);
		 OreDictionary.registerOre("compressed1xQuartzChiseled", CBlocks.compressedQuartzChiseled);
		 OreDictionary.registerOre("compressed2xQuartzChiseled", CBlocks.doublecompressedQuartzChiseled);
		 OreDictionary.registerOre("compressed3xQuartzChiseled", CBlocks.triplecompressedQuartzChiseled);
		 OreDictionary.registerOre("compressed4xQuartzChiseled", CBlocks.quadruplecompressedQuartzChiseled);
		 OreDictionary.registerOre("compressed1xQuartzLines", CBlocks.compressedQuartzLines);
		 OreDictionary.registerOre("compressed2xQuartzLines", CBlocks.doublecompressedQuartzLines);
		 OreDictionary.registerOre("compressed3xQuartzLines", CBlocks.triplecompressedQuartzLines);
		 OreDictionary.registerOre("compressed4xQuartzLines", CBlocks.quadruplecompressedQuartzLines);
		 OreDictionary.registerOre("compressed1xTNT", CBlocks.compressedTNT);
		 OreDictionary.registerOre("compressed2xTNT", CBlocks.doublecompressedTNT);
		 OreDictionary.registerOre("compressed3xTNT", CBlocks.triplecompressedTNT);
		 OreDictionary.registerOre("compressed4xTNT", CBlocks.quadruplecompressedTNT);
		 OreDictionary.registerOre("compressed1xSoulSand", CBlocks.compressedSoulSand);
		 OreDictionary.registerOre("compressed2xSoulSand", CBlocks.doublecompressedSoulSand);
		 OreDictionary.registerOre("compressed3xSoulSand", CBlocks.triplecompressedSoulSand);
		 OreDictionary.registerOre("compressed4xSoulSand", CBlocks.quadruplecompressedSoulSand);	 
		 for (int i = 0; i < EnumHandler.WoodTypes.values().length; i++) {
			 OreDictionary.registerOre("compressed1xWoodLog", (new ItemStack(CBlocks.compressedWoodLog, i)));
			 OreDictionary.registerOre("compressed2xWoodLog", (new ItemStack(CBlocks.doublecompressedWoodLog, i)));
			 OreDictionary.registerOre("compressed3xWoodLog", (new ItemStack(CBlocks.triplecompressedWoodLog, i)));
			 OreDictionary.registerOre("compressed4xWoodLog", (new ItemStack(CBlocks.quadruplecompressedWoodLog, i)));
		 }
		 OreDictionary.registerOre("compressed1xMelon", CBlocks.compressedMelon);
		 OreDictionary.registerOre("compressed2xMelon", CBlocks.doublecompressedMelon);
		 OreDictionary.registerOre("compressed3xMelon", CBlocks.triplecompressedMelon);
		 OreDictionary.registerOre("compressed4xMelon", CBlocks.quadruplecompressedMelon);		 
		 OreDictionary.registerOre("compressed1xJackOLantern", CBlocks.compressedJackOLantern);
		 OreDictionary.registerOre("compressed2xJackOLantern", CBlocks.doublecompressedJackOLantern);
		 OreDictionary.registerOre("compressed3xJackOLantern", CBlocks.triplecompressedJackOLantern);
		 OreDictionary.registerOre("compressed4xJackOLantern", CBlocks.quadruplecompressedJackOLantern);		
		 OreDictionary.registerOre("compressed1xPumpkin", CBlocks.compressedPumpkin);
		 OreDictionary.registerOre("compressed2xPumpkin", CBlocks.doublecompressedPumpkin);
		 OreDictionary.registerOre("compressed3xPumpkin", CBlocks.triplecompressedPumpkin);
		 OreDictionary.registerOre("compressed4xPumpkin", CBlocks.quadruplecompressedPumpkin);		
		 
		 
		 CLogger.getLogger().info("Ore Dictionary loaded");
	}

}
